services:

  # -----------------------------------------------------------------
  #  PUBLISHER SERVICES (EmployeeManagementSolu)
  # -----------------------------------------------------------------
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    container_name: employee-api-container
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    networks:
      - dapr-network

  presentation-dapr:
    image: "daprio/dapr:1.16.0"
    container_name: dapr_container
    network_mode: service:presentation
    command: [
      "/daprd",
      "-app-id", "employeeservice",
      "-app-port", "8080",
      "-resources-path", "/app"
    ]
    volumes:
      - ./rabbitmq-pubsub.yaml:/app/rabbitmq-pubsub.yaml
  
  # -----------------------------------------------------------------
  #  KEYCLOAK SERVICE
  # -----------------------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - dapr-network

  # -----------------------------------------------------------------
  #  SERVICES
  # -----------------------------------------------------------------
  mongodb-service:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "3000:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dapr-network

volumes:
  mongo-data:
  keycloak-data:

networks:
  dapr-network:
    external: true
    name: dapr-pubsub-network
    