services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    container_name: employee-api-container
    build:
      context: .
      dockerfile: Presentation/Dockerfile

  mongodb-service:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: