services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    container_name: employee-api-container
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  mongodb-service:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "3000:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq: 
    image: rabbitmq:management
    container_name: rabbitmq_container
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 20s

volumes:
  mongo-data:
    